((haskell-mode . ((haskell-indent-spaces . 4)
                  (haskell-process-type . ghci)
                  (haskell-process-path-ghci . "stack")
                  (haskell-process-args-ghci . ("ghci" "--ghc-options" "-XOverloadedStrings"))))
 (hamlet-mode . ((hamlet/basic-offset . 4)
                 (haskell-process-use-ghci . t))))
